[package]
name = "discord"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
serde = "1.0"
serde_derive = "1.0"
log = {version = "0.4", features=["std"]}
