[package]
name = "discord"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
serde = {version = "1.0", features=["derive"]}
log = {version = "0.4", features=["std"]}
